# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "${DB_PORT}:${DB_PORT}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080